apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-exchange
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - image: in28min/currency-exchange:2.0.0-RELEASE #CHANGE
        imagePullPolicy: Always #CHANGE
        name: currency-exchange
        env: #CHANGE
        - name: SPRING_CLOUD_GCP_TRACE_ENABLED
          value: "true"    
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: currency-exchange
  name: currency-exchange
  namespace: default
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 8000 #CHANGE
    protocol: TCP
    targetPort: 8000 #CHANGE
  selector:
    app: currency-exchange
  sessionAffinity: None #CHANGE
  type: LoadBalancer