name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Environment
        default: dev
        required: true
jobs:
  bump-version:
    name: Bump Package Versio
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usag
        run: git tag ${{ github.event.inputs.version }}
